# Generated by Django 4.1 on 2023-06-06 06:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Chat",
            fields=[
                ("c_id", models.AutoField(primary_key=True, serialize=False)),
                ("c_name", models.CharField(default="", max_length=255)),
                ("c_description", models.CharField(default="", max_length=255)),
                ("c_create_time", models.DateTimeField(auto_now_add=True)),
                ("c_last_modify_time", models.DateTimeField(auto_now_add=True)),
                ("c_heat", models.IntegerField(default=0)),
                ("c_tag", models.CharField(default="", max_length=255)),
            ],
            options={"db_table": "Chat", "managed": True,},
        ),
        migrations.CreateModel(
            name="Group",
            fields=[
                ("g_id", models.AutoField(primary_key=True, serialize=False)),
                ("g_name", models.CharField(max_length=255)),
                ("g_description", models.CharField(default="", max_length=255)),
                ("g_create_time", models.DateTimeField(auto_now_add=True)),
                ("g_last_modify_time", models.DateTimeField(auto_now_add=True)),
                ("g_tag", models.CharField(default="", max_length=255)),
                ("g_nickname", models.CharField(default="人", max_length=255)),
            ],
            options={"db_table": "Group", "managed": True,},
        ),
        migrations.CreateModel(
            name="Media",
            fields=[
                ("m_id", models.AutoField(primary_key=True, serialize=False)),
                ("m_name", models.CharField(default="", max_length=255)),
                ("m_type", models.IntegerField(default=0)),
                ("m_rate", models.FloatField(default=0)),
                ("m_rate_num", models.IntegerField(default=0)),
                ("m_genre", models.CharField(default="", max_length=255)),
                ("m_description", models.TextField(default="", max_length=65535)),
                ("m_year", models.IntegerField(default=0)),
                ("m_region", models.CharField(default="", max_length=255)),
                ("m_language", models.CharField(default="", max_length=255)),
                ("m_heat", models.IntegerField(default=0)),
                (
                    "m_director",
                    models.CharField(blank=True, default="", max_length=255, null=True),
                ),
                (
                    "m_actor",
                    models.CharField(blank=True, default="", max_length=255, null=True),
                ),
                (
                    "m_episode_num",
                    models.IntegerField(blank=True, default=0, null=True),
                ),
                ("m_duration", models.IntegerField(blank=True, default=0, null=True)),
                (
                    "m_author",
                    models.CharField(blank=True, default="", max_length=255, null=True),
                ),
                ("m_characters", models.IntegerField(blank=True, default=0, null=True)),
            ],
            options={"db_table": "Media", "managed": True,},
        ),
        migrations.CreateModel(
            name="Picture",
            fields=[
                ("p_id", models.AutoField(primary_key=True, serialize=False)),
                ("p_content", models.ImageField(upload_to="")),
            ],
            options={"db_table": "Picture", "managed": True,},
        ),
        migrations.CreateModel(
            name="Post",
            fields=[
                ("p_id", models.AutoField(primary_key=True, serialize=False)),
                ("p_title", models.CharField(default="", max_length=255)),
                ("p_like", models.IntegerField(default=0)),
                ("p_dislike", models.IntegerField(default=0)),
                ("p_create_time", models.DateTimeField(auto_now_add=True)),
                ("p_is_essence", models.IntegerField(default=0)),
                ("p_is_top", models.IntegerField(default=0)),
                ("p_floor_num", models.IntegerField(default=0)),
                (
                    "p_chat",
                    models.ForeignKey(
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="models.chat",
                    ),
                ),
                (
                    "p_group",
                    models.ForeignKey(
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="models.group",
                    ),
                ),
            ],
            options={"db_table": "Post", "managed": True,},
        ),
        migrations.CreateModel(
            name="Text",
            fields=[
                ("t_id", models.AutoField(primary_key=True, serialize=False)),
                ("t_type", models.IntegerField()),
                ("t_rate", models.FloatField(default=0)),
                ("t_like", models.IntegerField(default=0)),
                ("t_dislike", models.IntegerField(default=0)),
                ("t_description", models.TextField(default="")),
                ("t_topic", models.CharField(default="", max_length=255)),
                ("t_create_time", models.DateTimeField(auto_now_add=True)),
                ("t_floor", models.IntegerField(blank=True, default=0, null=True)),
                (
                    "t_media",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="models.media",
                    ),
                ),
                (
                    "t_post",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="models.post",
                    ),
                ),
                (
                    "t_text",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="models.text",
                    ),
                ),
            ],
            options={"db_table": "Text", "managed": True,},
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                ("u_id", models.AutoField(primary_key=True, serialize=False)),
                ("u_name", models.CharField(max_length=255)),
                ("u_password", models.CharField(max_length=255)),
                ("u_email", models.EmailField(default="", max_length=255)),
                ("u_authority", models.IntegerField(default=1)),
                ("is_active", models.BooleanField(default=False)),
            ],
            options={"db_table": "User", "managed": True,},
        ),
        migrations.CreateModel(
            name="UserText",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_liked", models.IntegerField(default=0)),
                ("is_disliked", models.IntegerField(default=0)),
                (
                    "text",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING, to="models.text"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING, to="models.user"
                    ),
                ),
            ],
            options={"db_table": "UserText", "managed": True,},
        ),
        migrations.CreateModel(
            name="UserPost",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_liked", models.IntegerField(default=0)),
                ("is_disliked", models.IntegerField(default=0)),
                ("is_favorite", models.IntegerField(default=0)),
                (
                    "post",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING, to="models.post"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING, to="models.user"
                    ),
                ),
            ],
            options={"db_table": "UserPost", "managed": True,},
        ),
        migrations.CreateModel(
            name="UserMedia",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_in_collection", models.IntegerField(default=0)),
                ("is_to_be_watched", models.IntegerField(default=0)),
                ("is_watching", models.IntegerField(default=0)),
                ("is_watched", models.IntegerField(default=0)),
                (
                    "media",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="models.media",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING, to="models.user"
                    ),
                ),
            ],
            options={"db_table": "UserMedia", "managed": True,},
        ),
        migrations.CreateModel(
            name="UserGroup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_admin", models.IntegerField(default=0)),
                ("is_member", models.IntegerField(default=0)),
                ("join_time", models.DateTimeField(auto_now_add=True)),
                ("user_heat", models.IntegerField(default=0)),
                (
                    "group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="models.group",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING, to="models.user"
                    ),
                ),
            ],
            options={"db_table": "UserGroup", "managed": True,},
        ),
        migrations.CreateModel(
            name="UserChat",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_admin", models.IntegerField(default=0)),
                ("join_time", models.DateTimeField(auto_now_add=True)),
                ("user_heat", models.IntegerField(default=0)),
                (
                    "chat",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING, to="models.chat"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING, to="models.user"
                    ),
                ),
            ],
            options={"db_table": "UserChat", "managed": True,},
        ),
        migrations.AddField(
            model_name="user",
            name="u_medias",
            field=models.ManyToManyField(
                related_name="m_users", through="models.UserMedia", to="models.media"
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="u_posts",
            field=models.ManyToManyField(
                related_name="p_users", through="models.UserPost", to="models.post"
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="u_profile_photo",
            field=models.ForeignKey(
                db_column="u_profile_photo",
                default=None,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="models.picture",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="u_texts",
            field=models.ManyToManyField(
                related_name="t_users", through="models.UserText", to="models.text"
            ),
        ),
        migrations.AddField(
            model_name="text",
            name="t_user",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="models.user",
            ),
        ),
        migrations.AddField(
            model_name="post",
            name="p_user",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                to="models.user",
            ),
        ),
        migrations.AddField(
            model_name="picture",
            name="p_father_text",
            field=models.ForeignKey(
                blank=True,
                db_column="p_father_text",
                default=None,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="models.text",
            ),
        ),
        migrations.AddField(
            model_name="picture",
            name="p_media",
            field=models.ForeignKey(
                blank=True,
                db_column="p_media",
                default=None,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="models.media",
            ),
        ),
        migrations.CreateModel(
            name="Message",
            fields=[
                (
                    "m_id",
                    models.AutoField(default=None, primary_key=True, serialize=False),
                ),
                ("m_time", models.DateTimeField(auto_now_add=True)),
                ("m_title", models.CharField(max_length=255)),
                ("m_description", models.CharField(max_length=255)),
                ("m_type", models.IntegerField()),
                (
                    "m_applier",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="applier",
                        to="models.user",
                    ),
                ),
                (
                    "m_group",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="applier",
                        to="models.group",
                    ),
                ),
                (
                    "m_post",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="models.post",
                    ),
                ),
                (
                    "m_text",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="models.text",
                    ),
                ),
                (
                    "m_user",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="user",
                        to="models.user",
                    ),
                ),
            ],
            options={"db_table": "Apply", "managed": True,},
        ),
        migrations.CreateModel(
            name="MediaGroup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="models.group",
                    ),
                ),
                (
                    "media",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="models.media",
                    ),
                ),
            ],
            options={"db_table": "MediaGroup", "managed": True,},
        ),
        migrations.CreateModel(
            name="MediaChat",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "chat",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING, to="models.chat"
                    ),
                ),
                (
                    "media",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="models.media",
                    ),
                ),
            ],
            options={"db_table": "MediaChat", "managed": True,},
        ),
        migrations.AddField(
            model_name="media",
            name="m_profile_photo",
            field=models.ForeignKey(
                db_column="m_profile_photo",
                default=None,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="models.picture",
            ),
        ),
        migrations.AddField(
            model_name="group",
            name="g_head_photo",
            field=models.ForeignKey(
                default=None,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="g_head_photo",
                to="models.picture",
            ),
        ),
        migrations.AddField(
            model_name="group",
            name="g_medias",
            field=models.ManyToManyField(
                related_name="m_groups", through="models.MediaGroup", to="models.media"
            ),
        ),
        migrations.AddField(
            model_name="group",
            name="g_profile_photo",
            field=models.ForeignKey(
                default=None,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="g_profile_photo",
                to="models.picture",
            ),
        ),
        migrations.AddField(
            model_name="group",
            name="g_users",
            field=models.ManyToManyField(
                related_name="u_groups", through="models.UserGroup", to="models.user"
            ),
        ),
        migrations.AddField(
            model_name="chat",
            name="c_father_group",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                to="models.group",
            ),
        ),
        migrations.AddField(
            model_name="chat",
            name="c_medias",
            field=models.ManyToManyField(
                related_name="m_chats", through="models.MediaChat", to="models.media"
            ),
        ),
        migrations.AddField(
            model_name="chat",
            name="c_profile_photo",
            field=models.ForeignKey(
                db_column="m_profile_photo",
                default=None,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="models.picture",
            ),
        ),
        migrations.AddField(
            model_name="chat",
            name="c_users",
            field=models.ManyToManyField(
                related_name="u_chats", through="models.UserChat", to="models.user"
            ),
        ),
    ]
