# Generated by Django 4.1 on 2023-05-23 13:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Media',
            fields=[
                ('m_id', models.AutoField(primary_key=True, serialize=False)),
                ('m_name', models.CharField(max_length=255)),
                ('m_type', models.IntegerField()),
                ('m_rate', models.FloatField(default=0)),
                ('m_rate_num', models.IntegerField(default=0)),
                ('m_heat', models.IntegerField(default=0)),
                ('m_genre', models.CharField(default='', max_length=255)),
                ('m_description', models.TextField(default='', max_length=65535)),
                ('m_time', models.IntegerField(default=None)),
                ('m_region', models.CharField(default='', max_length=255)),
                ('m_director', models.CharField(default='', max_length=255)),
                ('m_actor', models.CharField(default='', max_length=255)),
                ('m_episode_num', models.IntegerField(default=0)),
                ('m_author', models.CharField(default='', max_length=255)),
            ],
            options={
                'db_table': 'Media',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Picture',
            fields=[
                ('p_id', models.AutoField(primary_key=True, serialize=False)),
                ('p_content', models.ImageField(upload_to='')),
            ],
            options={
                'db_table': 'Picture',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Text',
            fields=[
                ('t_id', models.AutoField(primary_key=True, serialize=False)),
                ('t_type', models.IntegerField()),
                ('t_rate', models.FloatField(default=None)),
                ('t_like', models.IntegerField(default=0)),
                ('t_dislike', models.IntegerField(default=0)),
                ('t_description', models.TextField(default='')),
                ('t_topic', models.CharField(default='', max_length=255)),
                ('t_create_time', models.DateTimeField(auto_now=True)),
                ('t_father', models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='models.text')),
                ('t_media', models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='models.media')),
            ],
            options={
                'db_table': 'Text',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('u_id', models.AutoField(primary_key=True, serialize=False)),
                ('u_name', models.CharField(max_length=255)),
                ('u_password', models.CharField(max_length=255)),
                ('u_email', models.EmailField(default=None, max_length=255)),
                ('u_medias', models.ManyToManyField(related_name='m_users', to='models.media')),
                ('u_profile_photo', models.ForeignKey(db_column='u_profile_photo', default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='models.picture')),
            ],
            options={
                'db_table': 'User',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='UserText',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_liked', models.IntegerField(default=0)),
                ('is_disliked', models.IntegerField(default=0)),
                ('text', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='models.text')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='models.user')),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='u_texts',
            field=models.ManyToManyField(related_name='t_users', through='models.UserText', to='models.text'),
        ),
        migrations.AddField(
            model_name='text',
            name='t_user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='models.user'),
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('r_id', models.AutoField(primary_key=True, serialize=False)),
                ('r_details', models.TextField()),
                ('r_text', models.ForeignKey(default='', on_delete=django.db.models.deletion.DO_NOTHING, to='models.text')),
                ('r_user', models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='models.user')),
            ],
            options={
                'db_table': 'Report',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='picture',
            name='p_father_text',
            field=models.ForeignKey(db_column='p_father_text', default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='models.text'),
        ),
        migrations.AddField(
            model_name='media',
            name='m_profile_photo',
            field=models.ForeignKey(db_column='m_profile_photo', default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='models.picture'),
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('g_id', models.AutoField(primary_key=True, serialize=False)),
                ('g_name', models.CharField(max_length=255)),
                ('g_description', models.CharField(default='', max_length=255)),
                ('g_create_time', models.DateTimeField(auto_now=True)),
                ('g_last_modify_time', models.DateTimeField(auto_now=True)),
                ('g_medias', models.ManyToManyField(related_name='m_groups', to='models.media')),
                ('g_profile_photo', models.ForeignKey(db_column='g_profile_photo', default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='models.picture')),
                ('g_users', models.ManyToManyField(related_name='u_groups', to='models.user')),
            ],
            options={
                'db_table': 'Group',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('c_id', models.AutoField(primary_key=True, serialize=False)),
                ('c_name', models.CharField(max_length=255)),
                ('c_description', models.CharField(default='', max_length=255)),
                ('c_create_time', models.DateTimeField(auto_now=True)),
                ('c_last_modify_date', models.DateTimeField(auto_now=True)),
                ('c_father_group', models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='models.group')),
                ('c_medias', models.ManyToManyField(related_name='m_chats', to='models.media')),
                ('c_profile_photo', models.ForeignKey(db_column='m_profile_photo', default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='models.picture')),
                ('c_users', models.ManyToManyField(related_name='u_chats', to='models.user')),
            ],
            options={
                'db_table': 'Chat',
                'managed': True,
            },
        ),
    ]
