# Generated by Django 4.1 on 2023-06-06 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermedia',
            name='rate',
            field=models.IntegerField(default=0),
        ),
    ]
