# Generated by Django 4.1 on 2023-06-06 07:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("models", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="chat",
            name="c_head_photo",
            field=models.ForeignKey(
                default=None,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="c_head_photo",
                to="models.picture",
            ),
        ),
        migrations.AlterField(
            model_name="chat",
            name="c_profile_photo",
            field=models.ForeignKey(
                default=None,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="c_profile_photo",
                to="models.picture",
            ),
        ),
    ]
