# Generated by Django 4.1 on 2023-05-16 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("models", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="picture",
            name="p_content",
            field=models.ImageField(
                upload_to="D:\\Personal\\computing\\SE\\postmanroot\\SEimages"
            ),
        ),
    ]
