# Generated by Django 4.1 on 2023-05-27 18:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("models", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(model_name="post", name="p_first_floor_text",),
        migrations.AlterField(
            model_name="text",
            name="t_post",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="models.post",
            ),
        ),
    ]
