# Generated by Django 4.1 on 2023-06-06 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("models", "0002_chat_c_head_photo_alter_chat_c_profile_photo"),
    ]

    operations = [
        migrations.AddField(
            model_name="usertext",
            name="is_favorite",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="group",
            name="g_name",
            field=models.CharField(default="", max_length=255),
        ),
        migrations.AlterField(
            model_name="user",
            name="u_name",
            field=models.CharField(default="", max_length=255),
        ),
    ]
