# Generated by Django 4.1 on 2023-05-27 18:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("models", "0002_remove_post_p_first_floor_text_alter_text_t_post"),
    ]

    operations = [
        migrations.AddField(
            model_name="chat",
            name="c_tag",
            field=models.CharField(default="", max_length=255),
        ),
        migrations.AlterField(
            model_name="chat",
            name="c_name",
            field=models.CharField(default="", max_length=255),
        ),
        migrations.AlterField(
            model_name="text",
            name="t_media",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="models.media",
            ),
        ),
        migrations.AlterField(
            model_name="text",
            name="t_text",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="models.text",
            ),
        ),
    ]
