# Generated by Django 4.1 on 2023-05-24 02:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0002_alter_picture_p_father_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='picture',
            name='p_father_text',
            field=models.ForeignKey(db_column='p_father_text', default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='models.text'),
        ),
    ]
