# Generated by Django 4.1 on 2023-05-16 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("models", "0002_alter_picture_p_content"),
    ]

    operations = [
        migrations.AlterField(
            model_name="picture",
            name="p_content",
            field=models.ImageField(upload_to="images"),
        ),
    ]
