# Generated by Django 4.1 on 2023-05-24 02:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0003_alter_picture_p_father_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='c_profile_photo',
            field=models.ForeignKey(db_column='m_profile_photo', default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='models.picture'),
        ),
        migrations.AlterField(
            model_name='group',
            name='g_profile_photo',
            field=models.ForeignKey(db_column='g_profile_photo', default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='models.picture'),
        ),
        migrations.AlterField(
            model_name='media',
            name='m_profile_photo',
            field=models.ForeignKey(db_column='m_profile_photo', default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='models.picture'),
        ),
        migrations.AlterField(
            model_name='user',
            name='u_profile_photo',
            field=models.ForeignKey(db_column='u_profile_photo', default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='models.picture'),
        ),
    ]
