# Generated by Django 4.1 on 2023-06-06 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("models", "0003_usertext_is_favorite_alter_group_g_name_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="post", name="p_favorite", field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="post", name="p_heat", field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="text", name="t_favorite", field=models.IntegerField(default=0),
        ),
    ]
