# Generated by Django 4.1 on 2023-05-28 08:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("models", "0003_chat_c_tag_alter_chat_c_name_alter_text_t_media_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="chat",
            name="c_father_group",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                to="models.group",
            ),
        ),
        migrations.AlterField(
            model_name="post",
            name="p_chat",
            field=models.ForeignKey(
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="models.chat",
            ),
        ),
        migrations.AlterField(
            model_name="post",
            name="p_group",
            field=models.ForeignKey(
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="models.group",
            ),
        ),
        migrations.AlterField(
            model_name="post",
            name="p_user",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                to="models.user",
            ),
        ),
    ]
