# Generated by Django 4.1 on 2023-05-19 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("models", "0004_alter_picture_p_content"),
    ]

    operations = [
        migrations.AlterField(
            model_name="picture",
            name="p_content",
            field=models.ImageField(upload_to=""),
        ),
    ]
