# Generated by Django 4.1 on 2023-05-24 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0004_alter_chat_c_profile_photo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='u_email',
            field=models.EmailField(default='', max_length=255),
        ),
    ]
