# Generated by Django 4.1 on 2023-05-20 08:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0004_alter_picture_p_content'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chat',
            name='c_father_group_id',
        ),
        migrations.RemoveField(
            model_name='picture',
            name='p_father_text_id',
        ),
        migrations.AddField(
            model_name='chat',
            name='c_father_group',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='models.group'),
        ),
        migrations.AddField(
            model_name='picture',
            name='p_father_text',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='models.text'),
        ),
        migrations.AlterField(
            model_name='chat',
            name='c_create_time',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='chat',
            name='c_last_modify_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='chat',
            name='c_profile_photo',
            field=models.ForeignKey(db_column='m_profile_photo', default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='models.picture'),
        ),
        migrations.AlterField(
            model_name='group',
            name='g_create_time',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='group',
            name='g_last_modify_time',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='group',
            name='g_profile_photo',
            field=models.ForeignKey(db_column='m_profile_photo', default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='models.picture'),
        ),
        migrations.AlterField(
            model_name='media',
            name='m_heat',
            field=models.IntegerField(default=None),
        ),
        migrations.AlterField(
            model_name='media',
            name='m_json',
            field=models.JSONField(default=None),
        ),
        migrations.AlterField(
            model_name='media',
            name='m_profile_photo',
            field=models.ForeignKey(db_column='m_profile_photo', default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='models.picture'),
        ),
        migrations.AlterField(
            model_name='media',
            name='m_rate',
            field=models.FloatField(default=None),
        ),
        migrations.AlterField(
            model_name='media',
            name='m_rate_num',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='picture',
            name='p_content',
            field=models.ImageField(upload_to=None),
        ),
        migrations.AlterField(
            model_name='report',
            name='r_text',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='models.text'),
        ),
        migrations.AlterField(
            model_name='report',
            name='r_user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='models.user'),
        ),
        migrations.AlterField(
            model_name='text',
            name='t_description',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='text',
            name='t_dislike',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='text',
            name='t_father',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='models.text'),
        ),
        migrations.AlterField(
            model_name='text',
            name='t_like',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='text',
            name='t_media',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='models.media'),
        ),
        migrations.AlterField(
            model_name='text',
            name='t_rate',
            field=models.FloatField(default=None),
        ),
        migrations.AlterField(
            model_name='text',
            name='t_topic',
            field=models.CharField(default=None, max_length=255),
        ),
        migrations.AlterField(
            model_name='text',
            name='t_user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='models.user'),
        ),
        migrations.AlterField(
            model_name='user',
            name='u_email',
            field=models.EmailField(default=None, max_length=255),
        ),
        migrations.AlterField(
            model_name='user',
            name='u_profile_photo',
            field=models.ForeignKey(db_column='u_profile_photo', default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='models.picture'),
        ),
    ]
