# Generated by Django 4.1 on 2023-05-29 13:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("models", "0004_alter_chat_c_father_group_alter_post_p_chat_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user", name="u_authority", field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name="text", name="t_rate", field=models.FloatField(default=0),
        ),
        migrations.CreateModel(
            name="Apply",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("type", models.IntegerField()),
                ("info", models.CharField(max_length=255)),
                (
                    "admin",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="admin",
                        to="models.user",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="user",
                        to="models.user",
                    ),
                ),
            ],
        ),
    ]
