# Generated by Django 4.1 on 2023-06-07 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("models", "0004_post_p_favorite_post_p_heat_text_t_favorite"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user", name="is_active", field=models.IntegerField(default=0),
        ),
    ]
