# Generated by Django 4.1 on 2023-06-07 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0005_alter_user_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='media',
            name='m_page',
            field=models.IntegerField(default=0),
        ),
    ]
