# Generated by Django 4.1 on 2023-05-20 08:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("models", "0005_alter_picture_p_content"),
        ("models", "0005_remove_chat_c_father_group_id_and_more"),
    ]

    operations = []
