# Generated by Django 4.1 on 2023-05-25 01:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0005_alter_user_u_email'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mediachat',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='mediagroup',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='userchat',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='usergroup',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='usermedia',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='usertext',
            options={'managed': True},
        ),
        migrations.AlterModelTable(
            name='mediachat',
            table='MediaChat',
        ),
        migrations.AlterModelTable(
            name='mediagroup',
            table='MediaGroup',
        ),
        migrations.AlterModelTable(
            name='userchat',
            table='UserChat',
        ),
        migrations.AlterModelTable(
            name='usergroup',
            table='UserGroup',
        ),
        migrations.AlterModelTable(
            name='usermedia',
            table='UserMedia',
        ),
        migrations.AlterModelTable(
            name='usertext',
            table='UserText',
        ),
    ]
