# Generated by Django 4.1 on 2023-05-25 12:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0006_alter_mediachat_options_alter_mediagroup_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='text',
            name='t_father',
        ),
        migrations.AddField(
            model_name='text',
            name='t_floor',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='text',
            name='t_text',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='models.text'),
        ),
        migrations.AlterField(
            model_name='text',
            name='t_media',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='models.media'),
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('p_id', models.AutoField(primary_key=True, serialize=False)),
                ('p_title', models.CharField(default='', max_length=255)),
                ('p_like', models.IntegerField(default=0)),
                ('p_dislike', models.IntegerField(default=0)),
                ('p_create_time', models.DateTimeField(auto_now=True)),
                ('p_chat', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='models.chat')),
                ('p_first_floor_text', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='models.text')),
            ],
            options={
                'db_table': 'Post',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='text',
            name='t_post',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='models.post'),
        ),
    ]
