# Generated by Django 4.1 on 2023-06-07 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0006_media_m_page'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='u_birthday',
            field=models.CharField(blank=True, default='保密', max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='u_gender',
            field=models.CharField(blank=True, default='保密', max_length=16, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='u_nickname',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='u_signature',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
    ]
