# Generated by Django 4.1 on 2023-06-07 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0007_user_u_birthday_user_u_gender_user_u_nickname_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='u_desc',
            field=models.CharField(blank=True, default='', max_length=2048, null=True),
        ),
    ]
