# Generated by Django 4.1 on 2023-05-25 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0007_remove_text_t_father_text_t_floor_text_t_text_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='g_tag',
            field=models.CharField(default='', max_length=255),
        ),
    ]
