# Generated by Django 4.1 on 2023-05-20 08:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("models", "0007_alter_group_g_profile_photo_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="picture",
            name="p_father_text",
            field=models.ForeignKey(
                db_column="p_father_text",
                default=None,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="models.text",
            ),
        ),
    ]
