# Generated by Django 4.1 on 2023-05-20 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0008_alter_picture_p_father_text'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='media',
            name='m_json',
        ),
        migrations.AddField(
            model_name='media',
            name='m_actor',
            field=models.CharField(default=None, max_length=255),
        ),
        migrations.AddField(
            model_name='media',
            name='m_author',
            field=models.CharField(default=None, max_length=255),
        ),
        migrations.AddField(
            model_name='media',
            name='m_description',
            field=models.TextField(default=None, max_length=65535),
        ),
        migrations.AddField(
            model_name='media',
            name='m_director',
            field=models.CharField(default=None, max_length=255),
        ),
        migrations.AddField(
            model_name='media',
            name='m_episode_num',
            field=models.IntegerField(default=None),
        ),
        migrations.AddField(
            model_name='media',
            name='m_genre',
            field=models.CharField(default=None, max_length=255),
        ),
        migrations.AddField(
            model_name='media',
            name='m_region',
            field=models.CharField(default=None, max_length=255),
        ),
        migrations.AddField(
            model_name='media',
            name='m_time',
            field=models.IntegerField(default=None),
        ),
        migrations.AlterField(
            model_name='media',
            name='m_heat',
            field=models.IntegerField(default=0),
        ),
    ]
