# Generated by Django 4.1 on 2023-06-07 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0008_user_u_desc'),
    ]

    operations = [
        migrations.AddField(
            model_name='media',
            name='m_publisher',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
    ]
