# Generated by Django 4.1 on 2023-06-07 07:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("models", "0009_media_m_publisher"),
    ]

    operations = [
        migrations.AlterField(
            model_name="chat",
            name="c_father_group",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="models.group",
            ),
        ),
    ]
