# Generated by Django 4.1 on 2023-06-07 10:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("models", "0011_post_p_tag"),
    ]

    operations = [
        migrations.AlterModelTable(name="message", table="Message",),
    ]
