# Generated by Django 4.1 on 2023-06-07 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("models", "0013_message_m_is_handled"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user", name="u_authority", field=models.IntegerField(default=0),
        ),
    ]
