# Generated by Django 4.1 on 2023-06-07 19:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("models", "0015_alter_message_m_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="message",
            name="m_post",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="models.post",
            ),
        ),
        migrations.AlterField(
            model_name="userpost",
            name="post",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="models.post"
            ),
        ),
        migrations.AlterField(
            model_name="usertext",
            name="text",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="models.text"
            ),
        ),
    ]
