# Generated by Django 4.1 on 2023-06-08 05:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("models", "0016_alter_message_m_post_alter_userpost_post_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="chat",
            name="c_head_photo",
            field=models.ForeignKey(
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="c_head_photo",
                to="models.picture",
            ),
        ),
        migrations.AlterField(
            model_name="chat",
            name="c_profile_photo",
            field=models.ForeignKey(
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="c_profile_photo",
                to="models.picture",
            ),
        ),
        migrations.AlterField(
            model_name="group",
            name="g_head_photo",
            field=models.ForeignKey(
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="g_head_photo",
                to="models.picture",
            ),
        ),
        migrations.AlterField(
            model_name="group",
            name="g_profile_photo",
            field=models.ForeignKey(
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="g_profile_photo",
                to="models.picture",
            ),
        ),
        migrations.AlterField(
            model_name="media",
            name="m_profile_photo",
            field=models.ForeignKey(
                db_column="m_profile_photo",
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="models.picture",
            ),
        ),
        migrations.AlterField(
            model_name="mediachat",
            name="chat",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="models.chat"
            ),
        ),
        migrations.AlterField(
            model_name="mediachat",
            name="media",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="models.media"
            ),
        ),
        migrations.AlterField(
            model_name="mediagroup",
            name="group",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="models.group"
            ),
        ),
        migrations.AlterField(
            model_name="mediagroup",
            name="media",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="models.media"
            ),
        ),
        migrations.AlterField(
            model_name="message",
            name="m_applier",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="applier",
                to="models.user",
            ),
        ),
        migrations.AlterField(
            model_name="message",
            name="m_group",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="models.group",
            ),
        ),
        migrations.AlterField(
            model_name="message",
            name="m_text",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="models.text",
            ),
        ),
        migrations.AlterField(
            model_name="message",
            name="m_user",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="user",
                to="models.user",
            ),
        ),
        migrations.AlterField(
            model_name="picture",
            name="p_father_text",
            field=models.ForeignKey(
                blank=True,
                db_column="p_father_text",
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="models.text",
            ),
        ),
        migrations.AlterField(
            model_name="picture",
            name="p_media",
            field=models.ForeignKey(
                blank=True,
                db_column="p_media",
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="models.media",
            ),
        ),
        migrations.AlterField(
            model_name="text",
            name="t_user",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                to="models.user",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="u_profile_photo",
            field=models.ForeignKey(
                db_column="u_profile_photo",
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="models.picture",
            ),
        ),
        migrations.AlterField(
            model_name="userchat",
            name="chat",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="models.chat"
            ),
        ),
        migrations.AlterField(
            model_name="userchat",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="models.user"
            ),
        ),
        migrations.AlterField(
            model_name="usergroup",
            name="group",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="models.group"
            ),
        ),
        migrations.AlterField(
            model_name="usergroup",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="models.user"
            ),
        ),
        migrations.AlterField(
            model_name="usermedia",
            name="media",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="models.media"
            ),
        ),
        migrations.AlterField(
            model_name="usermedia",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="models.user"
            ),
        ),
        migrations.AlterField(
            model_name="userpost",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="models.user"
            ),
        ),
        migrations.AlterField(
            model_name="usertext",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="models.user"
            ),
        ),
    ]
