ERR_REQUEST_METHOD_WRONG = -1
ERR_USERNAME_EXISTS = -2
ERR_PASSWORD_NOT_SAME = -3
ERR_USER_NOT_EXISTS = -4
ERR_PASSWORD_WRONG = -5
ERR_NO_CURRENT_USER = -6
ERR_MEDIA_NOT_EXISTS = -7
ERR_GROUP_NOT_EXISTS = -8
ERR_CHAT_NOT_EXISTS = -9

CUR_USER_ID = 'cur_user_id'
DEFAULT_PROFILE_PHOTO_ID = 4  # make this right before running !!!
